#! -*-  coding=utf-8 -*-

from sqlalchemy.ext.declarative import declarative_base

from sqlalchemy import Column, Integer, String, Text

Base = declarative_base()

#　异常数据的数据表关系映射
class F_error_lname_data(Base):
    __tablename__ = 'f_error_lname_data'
    id = Column(Integer, primary_key=True, nullable=False, autoincrement=True)
    BYQ_t_id = Column(Text, nullable=True)
    cu_id1 = Column(Text, nullable=True)
    cu_loc1_name = Column(Text, nullable=True)
    cu_loc2_name = Column(Text, nullable=True)
    cu_name = Column(Text, nullable=True)
    collec_id = Column(Text, nullable=True)
    taiqu_id = Column(Text, nullable=True)
    shebei_id = Column(Text, nullable=True)
    taiqu_name = Column(Text, nullable=True)
    gong_zhuan = Column(Text, nullable=True)
    BYQT_line_id = Column(Text, nullable=True)
    Basic_line_id = Column(Text, nullable=True)
    line_num = Column(Text, nullable=True)
    Error_line_name = Column(Text, nullable=True)
    basicT_line_name = Column(Text, nullable=True)
    yonghu_id = Column(Text, nullable=True)
    yonghu_name = Column(Text, nullable=True)
    dianneng_id = Column(Text, nullable=True)
    getL_style_name = Column(Text, nullable=True)
    stopC_time = Column(Text, nullable=True)
    resumeC_time = Column(Text, nullable=True)
    stopC_timeL = Column(Text, nullable=True)
    Measure_dot = Column(Text, nullable=True)
    C_presue_Col_time = Column(Text, nullable=True)
    xiangyu = Column(Text, nullable=True)
    Data_fullSign = Column(Text, nullable=True)
    t0000 = Column(Text, nullable=True)
    t0015 = Column(Text, nullable=True)
    t0030 = Column(Text, nullable=True)
    t0045 = Column(Text, nullable=True)
    t0100 = Column(Text, nullable=True)
    t0115 = Column(Text, nullable=True)
    t0130 = Column(Text, nullable=True)
    t0145 = Column(Text, nullable=True)
    t0200 = Column(Text, nullable=True)
    t0215 = Column(Text, nullable=True)
    t0230 = Column(Text, nullable=True)
    t0245 = Column(Text, nullable=True)
    t0300 = Column(Text, nullable=True)
    t0315 = Column(Text, nullable=True)
    t0330 = Column(Text, nullable=True)
    t0345 = Column(Text, nullable=True)
    t0400 = Column(Text, nullable=True)
    t0415 = Column(Text, nullable=True)
    t0430 = Column(Text, nullable=True)
    t0445 = Column(Text, nullable=True)
    t0500 = Column(Text, nullable=True)
    t0515 = Column(Text, nullable=True)
    t0530 = Column(Text, nullable=True)
    t0545 = Column(Text, nullable=True)
    t0600 = Column(Text, nullable=True)
    t0615 = Column(Text, nullable=True)
    t0630 = Column(Text, nullable=True)
    t0645 = Column(Text, nullable=True)
    t0700 = Column(Text, nullable=True)
    t0715 = Column(Text, nullable=True)
    t0730 = Column(Text, nullable=True)
    t0745 = Column(Text, nullable=True)
    t0800 = Column(Text, nullable=True)
    t0815 = Column(Text, nullable=True)
    t0830 = Column(Text, nullable=True)
    t0845 = Column(Text, nullable=True)
    t0900 = Column(Text, nullable=True)
    t0915 = Column(Text, nullable=True)
    t0930 = Column(Text, nullable=True)
    t0945 = Column(Text, nullable=True)
    t1000 = Column(Text, nullable=True)
    t1015 = Column(Text, nullable=True)
    t1030 = Column(Text, nullable=True)
    t1045 = Column(Text, nullable=True)
    t1100 = Column(Text, nullable=True)
    t1115 = Column(Text, nullable=True)
    t1130 = Column(Text, nullable=True)
    t1145 = Column(Text, nullable=True)
    t1200 = Column(Text, nullable=True)
    t1215 = Column(Text, nullable=True)
    t1230 = Column(Text, nullable=True)
    t1245 = Column(Text, nullable=True)
    t1300 = Column(Text, nullable=True)
    t1315 = Column(Text, nullable=True)
    t1330 = Column(Text, nullable=True)
    t1345 = Column(Text, nullable=True)
    t1400 = Column(Text, nullable=True)
    t1415 = Column(Text, nullable=True)
    t1430 = Column(Text, nullable=True)
    t1445 = Column(Text, nullable=True)
    t1500 = Column(Text, nullable=True)
    t1515 = Column(Text, nullable=True)
    t1530 = Column(Text, nullable=True)
    t1545 = Column(Text, nullable=True)
    t1600 = Column(Text, nullable=True)
    t1615 = Column(Text, nullable=True)
    t1630 = Column(Text, nullable=True)
    t1645 = Column(Text, nullable=True)
    t1700 = Column(Text, nullable=True)
    t1715 = Column(Text, nullable=True)
    t1730 = Column(Text, nullable=True)
    t1745 = Column(Text, nullable=True)
    t1800 = Column(Text, nullable=True)
    t1815 = Column(Text, nullable=True)
    t1830 = Column(Text, nullable=True)
    t1845 = Column(Text, nullable=True)
    t1900 = Column(Text, nullable=True)
    t1915 = Column(Text, nullable=True)
    t1930 = Column(Text, nullable=True)
    t1945 = Column(Text, nullable=True)
    t2000 = Column(Text, nullable=True)
    t2015 = Column(Text, nullable=True)
    t2030 = Column(Text, nullable=True)
    t2045 = Column(Text, nullable=True)
    t2100 = Column(Text, nullable=True)
    t2115 = Column(Text, nullable=True)
    t2130 = Column(Text, nullable=True)
    t2145 = Column(Text, nullable=True)
    t2200 = Column(Text, nullable=True)
    t2215 = Column(Text, nullable=True)
    t2230 = Column(Text, nullable=True)
    t2245 = Column(Text, nullable=True)
    t2300 = Column(Text, nullable=True)
    t2315 = Column(Text, nullable=True)
    t2330 = Column(Text, nullable=True)
    t2345 = Column(Text, nullable=True)

    def to_json(self):
        dict = self.__dict__
        if "_sa_instance_state" in dict:
            del dict["_sa_instance_state"]
        return dict


# 变压器停电表关系映射
class B_byq_table(Base):
    __tablename__ = 'b_byq_table'
    id = Column(Integer, primary_key=True, nullable=False, autoincrement=True)
    BYQ_t_id = Column(Text, nullable=True)
    cu_id1 = Column(Text, nullable=True)
    cu_loc1_name = Column(Text, nullable=True)
    cu_loc2_name = Column(Text, nullable=True)
    cu_name = Column(Text, nullable=True)
    collec_id = Column(Text, nullable=True)
    taiqu_id = Column(Text, nullable=True)
    shebei_id = Column(Text, nullable=True)
    taiqu_name = Column(Text, nullable=True)
    gong_zhuan = Column(Text, nullable=True)
    line_id = Column(Text, nullable=True)
    line_num = Column(Text, nullable=True)
    line_name = Column(Text, nullable=True)
    yonghu_id = Column(Text, nullable=True)
    yonghu_name = Column(Text, nullable=True)
    dianneng_id = Column(Text, nullable=True)
    getL_style_name = Column(Text, nullable=True)
    stopC_time = Column(Text, nullable=True)
    resumeC_time = Column(Text, nullable=True)
    stopC_timeL = Column(Text, nullable=True)
    Measure_dot = Column(Text, nullable=True)
    C_presue_Col_time = Column(Text, nullable=True)
    xiangyu = Column(Text, nullable=True)
    Data_fullSign = Column(Text, nullable=True)
    t0000 = Column(Text, nullable=True)
    t0015 = Column(Text, nullable=True)
    t0030 = Column(Text, nullable=True)
    t0045 = Column(Text, nullable=True)
    t0100 = Column(Text, nullable=True)
    t0115 = Column(Text, nullable=True)
    t0130 = Column(Text, nullable=True)
    t0145 = Column(Text, nullable=True)
    t0200 = Column(Text, nullable=True)
    t0215 = Column(Text, nullable=True)
    t0230 = Column(Text, nullable=True)
    t0245 = Column(Text, nullable=True)
    t0300 = Column(Text, nullable=True)
    t0315 = Column(Text, nullable=True)
    t0330 = Column(Text, nullable=True)
    t0345 = Column(Text, nullable=True)
    t0400 = Column(Text, nullable=True)
    t0415 = Column(Text, nullable=True)
    t0430 = Column(Text, nullable=True)
    t0445 = Column(Text, nullable=True)
    t0500 = Column(Text, nullable=True)
    t0515 = Column(Text, nullable=True)
    t0530 = Column(Text, nullable=True)
    t0545 = Column(Text, nullable=True)
    t0600 = Column(Text, nullable=True)
    t0615 = Column(Text, nullable=True)
    t0630 = Column(Text, nullable=True)
    t0645 = Column(Text, nullable=True)
    t0700 = Column(Text, nullable=True)
    t0715 = Column(Text, nullable=True)
    t0730 = Column(Text, nullable=True)
    t0745 = Column(Text, nullable=True)
    t0800 = Column(Text, nullable=True)
    t0815 = Column(Text, nullable=True)
    t0830 = Column(Text, nullable=True)
    t0845 = Column(Text, nullable=True)
    t0900 = Column(Text, nullable=True)
    t0915 = Column(Text, nullable=True)
    t0930 = Column(Text, nullable=True)
    t0945 = Column(Text, nullable=True)
    t1000 = Column(Text, nullable=True)
    t1015 = Column(Text, nullable=True)
    t1030 = Column(Text, nullable=True)
    t1045 = Column(Text, nullable=True)
    t1100 = Column(Text, nullable=True)
    t1115 = Column(Text, nullable=True)
    t1130 = Column(Text, nullable=True)
    t1145 = Column(Text, nullable=True)
    t1200 = Column(Text, nullable=True)
    t1215 = Column(Text, nullable=True)
    t1230 = Column(Text, nullable=True)
    t1245 = Column(Text, nullable=True)
    t1300 = Column(Text, nullable=True)
    t1315 = Column(Text, nullable=True)
    t1330 = Column(Text, nullable=True)
    t1345 = Column(Text, nullable=True)
    t1400 = Column(Text, nullable=True)
    t1415 = Column(Text, nullable=True)
    t1430 = Column(Text, nullable=True)
    t1445 = Column(Text, nullable=True)
    t1500 = Column(Text, nullable=True)
    t1515 = Column(Text, nullable=True)
    t1530 = Column(Text, nullable=True)
    t1545 = Column(Text, nullable=True)
    t1600 = Column(Text, nullable=True)
    t1615 = Column(Text, nullable=True)
    t1630 = Column(Text, nullable=True)
    t1645 = Column(Text, nullable=True)
    t1700 = Column(Text, nullable=True)
    t1715 = Column(Text, nullable=True)
    t1730 = Column(Text, nullable=True)
    t1745 = Column(Text, nullable=True)
    t1800 = Column(Text, nullable=True)
    t1815 = Column(Text, nullable=True)
    t1830 = Column(Text, nullable=True)
    t1845 = Column(Text, nullable=True)
    t1900 = Column(Text, nullable=True)
    t1915 = Column(Text, nullable=True)
    t1930 = Column(Text, nullable=True)
    t1945 = Column(Text, nullable=True)
    t2000 = Column(Text, nullable=True)
    t2015 = Column(Text, nullable=True)
    t2030 = Column(Text, nullable=True)
    t2045 = Column(Text, nullable=True)
    t2100 = Column(Text, nullable=True)
    t2115 = Column(Text, nullable=True)
    t2130 = Column(Text, nullable=True)
    t2145 = Column(Text, nullable=True)
    t2200 = Column(Text, nullable=True)
    t2215 = Column(Text, nullable=True)
    t2230 = Column(Text, nullable=True)
    t2245 = Column(Text, nullable=True)
    t2300 = Column(Text, nullable=True)
    t2315 = Column(Text, nullable=True)
    t2330 = Column(Text, nullable=True)
    t2345 = Column(Text, nullable=True)

    def to_json(self):
        dict = self.__dict__
        if "_sa_instance_state" in dict:
            del dict["_sa_instance_state"]
        return dict


#基准表关系映射
class Basic_table(Base):
    __tablename__ = 'basic_table'
    id = Column(Integer, primary_key=True, nullable=False, autoincrement=True)
    TRAN_ID = Column(Text, nullable=True)
    TRAN_NAME = Column(Text, nullable=True)
    LINE_ID = Column(Text, nullable=True)
    LINE_NAME = Column(Text, nullable=True)

    def to_json(self):
        dict = self.__dict__
        if "_sa_instance_state" in dict:
            del dict["_sa_instance_state"]
        return dict
